import os
import smtplib
from email.message import EmailMessage
from datetime import datetime

SENDER_EMAIL = "levankhoi06092005@gmail.com"
APP_PASSWORD = "xhdpecnkcirxsbnz"

RECEIVER_EMAIL = "levankhoi692005@gmail.com"




def send_fall_email(image_path):

    try:

        current_time = datetime.now().strftime(
            "%d/%m/%Y %H:%M:%S"
        )
        msg = EmailMessage()

        msg["Subject"] = "🚨 FALL DETECTION SYSTEM ALERT"
        msg["From"] = SENDER_EMAIL
        msg["To"] = RECEIVER_EMAIL

        msg.set_content(
            f"""
        FALL DETECTION NOTIFICATION

        Detection Time:
        {current_time}

        Alert Level:
        HIGH

        Description:
        The monitoring system has detected a potential fall event.

        A snapshot captured at the moment of detection is attached for review.

        This email was automatically generated by the
        Human Fall Detection System based on YOLOv8 Pose Estimation.
        """
        )

        with open(image_path, "rb") as f:
            image_data = f.read()

        msg.add_attachment(
            image_data,
            maintype="image",
            subtype="jpeg",
            filename=os.path.basename(image_path)
        )

        with smtplib.SMTP_SSL(
                "smtp.gmail.com",
                465
        ) as smtp:

            smtp.login(
                SENDER_EMAIL,
                APP_PASSWORD
            )

            smtp.send_message(msg)

        print("[EMAIL] Sent successfully")

    except Exception as e:
        print("[EMAIL ERROR]", e)